### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ghost** [ionalexandru99/Cve.Mitre#38]
![grafik](https://user-images.githubusercontent.com/108922074/189615005-657dfede-5f04-465a-84ad-e4e5e6a01cc2.png)

I just wanted to test it, but my List shows no vulnerabilities.
Have i done something wrong?

**Comment by ionalexandru99** [comment]
Hi @masaeberle,

From what I can see you don't actually have any values in your List of SearchResults.
The role if the ICveProcessor is to make requests to the CVE.Mitre website and return to you search results or actual vulnerabilities.
The GetVulnerabilitiesAsync expects the srResults list to actually contain SearchResults.
You can try and use another method.

**Comment by ghost** [comment]
Hi, okay. Now i get it. But this here should work right? It doesn't work as well :) 
![grafik](https://user-images.githubusercontent.com/108922074/189628655-26b8affd-a44f-4a34-9a3a-74a5403bee66.png)

**Comment by ionalexandru99** [comment]
Hi @masaeberle, can you please leave a screen shot with the error(s) that you have? Also, are you using the latest version, 1.0.1?

**Comment by ionalexandru99** [comment]
I was testing locally and apparently the pipeline didn't deploy my last fix.
@masaeberle can you please update to version 1.1.0 and try again?

**Comment by ionalexandru99** [comment]
@masaeberle has the issue been fixed? Do you need any further assistance with anything?

**Comment by ionalexandru99** [comment]
Closing the issue due to no further details
